### ISSUE TITLE
Errors exporting skeletal mesh

### ISSUE THREAD

**Issue by slapin** [reattiva/Urho3D-Blender#59]
I imported Makehuman character with default skeleton and export it to Urho without much modifications.
This was working not so long ago, now I get:

Geometry0 remapping from 163 bones to 35 (29 free)
Traceback (most recent call last):
  File "/home/slapin/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/io_mesh_urho/__init__.py", line 834, in invoke
    return self.execute(context)
  File "/home/slapin/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/io_mesh_urho/__init__.py", line 830, in execute
    ExecuteAddon(context)
  File "/home/slapin/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/io_mesh_urho/__init__.py", line 1444, in ExecuteAddon
    ExecuteUrhoExport(context)
  File "/home/slapin/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/io_mesh_urho/__init__.py", line 1342, in ExecuteUrhoExport
    UrhoExport(tData, uExportOptions, uExportData, settings.errorsMem)
  File "/home/slapin/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/io_mesh_urho/export_urho.py", line 1121, in UrhoExport
    bone.boundingBox.max.y = bone.length
AttributeError: 'UrhoBone' object has no attribute 'length'

**Comment by Mike3D** [comment]
Sorry, I might have forgotten to push a line (355) in export_urho:
```
        self.boundingBox = BoundingBox()
        self.length = 0

**Comment by slapin** [comment]
Yep, this one is missing, thanks! Testing now (looks like it will take
about 2 additional days to export my character).

**Comment by reattiva** [comment]
Done!

**Comment by slapin** [comment]
Thanks!
